spring.application.name=msFoodCourt
server.port=8091

spring.datasource.url=jdbc:postgresql://localhost:5432/foodcourtdb
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret=401e7f3300ea452e8670811b64f0b06174b0cf4ecf90d9580895f595773c6804
jwt.expiration=3600000