spring.application.name=msFoodCourt
server.port=8091

spring.datasource.url=jdbc:postgresql://localhost:5432/foodcourtdb
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret=dm95YWVzdGFyZW5wcmFnbWFzaW9zaWVzdG9lc3VuZWFzdGVyZWdnOikjIyMjamVqZQ==
jwt.expiration=3600000